import type { Metadata } from "next";
import "../style/globals.css";
import Navbar from "@/components/navbar";
import { ContextProvider } from "@/context/context";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "mohammadtaha",
  description: "Generated by mohammadtaha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" sizes="32x32" />
      </head>

      <body>
        <ContextProvider>
          <Navbar />
          <div dir="rtl" className="min-h-screen">{children}</div>
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
